import { Link } from 'react-router-dom';

const Registration = () => {
  const earlyBirdFees = [
    { category: 'Student Authors (UG, PG, PhD)', ieee: '8260 INR', nonIEEE: '9440 INR' },
    { category: 'Academic Institution Delegates', ieee: '9440 INR', nonIEEE: '10620 INR' },
    { category: 'Industry / R&D Professionals', ieee: '11800 INR', nonIEEE: '12980 INR' },
    { category: 'Foreign Delegates', ieee: 'USD 295', nonIEEE: 'USD 354' }
  ];

  const regularFees = [
    { category: 'Student Authors', ieee: '9440 INR', nonIEEE: '10620 INR' },
    { category: 'Academic Institution Delegates', ieee: '10620 INR', nonIEEE: '11800 INR' },
    { category: 'Industry / R&D Professionals', ieee: '12980 INR', nonIEEE: '14160 INR' },
    { category: 'Foreign Delegates', ieee: 'USD 413', nonIEEE: 'USD 472' }
  ];

  const guidelines = [
    'The paper must be submitted in IEEE double column format A4 size, strictly adhering to the IEEE template for conference publications.',
    'AICARE 2025 conducts a plagiarism check on all submitted papers. Plagiarism and self-plagiarism apply to all works.',
    'Double blind peer review is done for all the submitted manuscripts.',
    'The maximum plagiarism percentage allowed for the conference is 20%. Turnitin/iThenticate is used to check plagiarism.',
    'At least one author of each accepted paper must register on/before 30th August 2025.',
    'Unregistered papers will not be included in the final program for presentation and submission to IEEE Xplore.',
    'Maximum Page length of a paper is 6.',
    'Each full registration is valid for one paper. Extra two pages (max 8 pages) may be allowed with an over length page charge of Rs. 3000/ $40 per page.',
    'Please keep a copy of the Payment Transaction ID, generated by the payment gateway / by your bank.',
    'The paid registration fee is non-refundable.',
    'The eligible authors are requested to provide the scan copy of valid IEEE membership card / Student Institute ID proof during the registration process.'
  ];

  return (
    <div className="min-h-screen bg-cover bg-center bg-fixed mt-8 lg:mt-20 pb-20" style={{ backgroundImage: "url('../assets/AboutBg.png')" }}>
      <div className="max-w-6xl mx-auto px-3 sm:px-4 py-6 sm:py-8 lg:py-12">
        {/* Header */}
        <div className="text-center mb-8 sm:mb-10 lg:mb-14">
          <h1 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-blue-600 mb-2 sm:mb-3 leading-tight">
            Registration Policy
          </h1>
          <div className="h-1 w-20 sm:w-24 md:w-32 bg-gradient-to-r from-blue-500 to-purple-500 mx-auto rounded-full"></div>
        </div>

        {/* Main Content */}
        <div className="bg-white bg-opacity-95 rounded-2xl shadow-xl p-4 sm:p-6 md:p-8 lg:p-10 space-y-6 sm:space-y-8">
          {/* Important Note */}
          <div className="bg-gradient-to-r from-blue-50 to-indigo-50 border-l-4 border-blue-600 p-4 sm:p-6 rounded-lg">
            <p className="text-gray-800 leading-relaxed text-xs sm:text-sm md:text-base lg:text-lg">
              At least one author of the accepted paper must register with an appropriate conference fee to include the paper in the <span className="font-bold">First AICARE-2025 conference program</span> and submission to <span className="font-bold">IEEE Xplore</span>. Final decision of uploading the presented paper will be taken by IEEE Xplore.
            </p>
          </div>

          {/* Guidelines Section */}
          <div className="border-t-2 border-gray-200 pt-4 sm:pt-6">
            <h2 className="text-xl sm:text-2xl md:text-3xl font-bold text-blue-600 mb-4 sm:mb-6">
              Guidelines
            </h2>
            <ul className="space-y-3 sm:space-y-4">
              {guidelines.map((guideline, idx) => (
                <li key={idx} className="flex gap-2 sm:gap-4">
                  <span className="text-blue-600 font-bold text-sm sm:text-base md:text-lg lg:text-xl flex-shrink-0 mt-0.5">{idx + 1}.</span>
                  <span className="text-gray-700 leading-relaxed text-xs sm:text-sm md:text-base">{guideline}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Early Bird Fees Table */}
          <div className="border-t-2 border-gray-200 pt-4 sm:pt-6">
            <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-blue-600 mb-4 sm:mb-6">
              Early Bird Registration Fees
            </h2>
            <div className="overflow-x-auto">
              <table className="w-full text-xs sm:text-sm border-collapse">
                <thead>
                  <tr className="bg-gradient-to-r from-blue-600 to-blue-800 text-white">
                    <th className="p-2 sm:p-4 text-left font-semibold text-xs sm:text-sm">Author Category</th>
                    <th className="p-2 sm:p-4 text-center font-semibold text-xs sm:text-sm">IEEE Members Fee</th>
                    <th className="p-2 sm:p-4 text-center font-semibold text-xs sm:text-sm">Non-IEEE Members Fee</th>
                  </tr>
                </thead>
                <tbody>
                  {earlyBirdFees.map((row, idx) => (
                    <tr key={idx} className={idx % 2 === 0 ? 'bg-blue-50' : 'bg-white'}>
                      <td className="p-2 sm:p-4 border-b border-gray-200 text-xs sm:text-sm">{row.category}</td>
                      <td className="p-2 sm:p-4 border-b border-gray-200 text-center font-semibold text-green-700 text-xs sm:text-sm">{row.ieee}</td>
                      <td className="p-2 sm:p-4 border-b border-gray-200 text-center font-semibold text-green-700 text-xs sm:text-sm">{row.nonIEEE}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Regular Fees Table */}
          <div className="border-t-2 border-gray-200 pt-4 sm:pt-6">
            <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-blue-600 mb-4 sm:mb-6">
              Regular Registration Fees
            </h2>
            <div className="overflow-x-auto">
              <table className="w-full text-xs sm:text-sm border-collapse">
                <thead>
                  <tr className="bg-gradient-to-r from-orange-600 to-orange-800 text-white">
                    <th className="p-2 sm:p-4 text-left font-semibold text-xs sm:text-sm">Author Category</th>
                    <th className="p-2 sm:p-4 text-center font-semibold text-xs sm:text-sm">IEEE Members Fee</th>
                    <th className="p-2 sm:p-4 text-center font-semibold text-xs sm:text-sm">Non-IEEE Members Fee</th>
                  </tr>
                </thead>
                <tbody>
                  {regularFees.map((row, idx) => (
                    <tr key={idx} className={idx % 2 === 0 ? 'bg-orange-50' : 'bg-white'}>
                      <td className="p-2 sm:p-4 border-b border-gray-200 text-xs sm:text-sm">{row.category}</td>
                      <td className="p-2 sm:p-4 border-b border-gray-200 text-center font-semibold text-orange-700 text-xs sm:text-sm">{row.ieee}</td>
                      <td className="p-2 sm:p-4 border-b border-gray-200 text-center font-semibold text-orange-700 text-xs sm:text-sm">{row.nonIEEE}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Payment Instructions */}
          <div className="border-t-2 border-gray-200 pt-4 sm:pt-6 bg-gray-50 rounded-lg p-4 sm:p-6">
            <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-blue-600 mb-4 sm:mb-6">Payment & Invoice Instructions</h2>
            
            {/* Indian Authors */}
            <div className="mb-6 sm:mb-8">
              <h3 className="text-base sm:text-lg md:text-xl font-bold text-gray-900 mb-3 sm:mb-4">
                For Indian Authors
              </h3>
              <div className="space-y-2 sm:space-y-3 ml-4 sm:ml-6 text-gray-700 text-xs sm:text-sm md:text-base">
                <p>
                  To register your Paper, please click: <a href="https://uem.edu.in/uem-kolkata/aicare-2025/" className="text-blue-600 font-semibold hover:underline">Registration Link</a>
                </p>
                <p>
                  After your paper gets registered, the author will receive an auto-generated e-mail. This e-mail will include an invoice containing the amount you paid for registration.
                </p>
                <p>
                  The author must e-mail that invoice to <a href="mailto:aicare@uem.edu.in" className="text-blue-600 font-semibold hover:underline">aicare@uem.edu.in</a> along with their paper ID and paper title. The file should be in PDF format and named as: <span className="font-mono bg-gray-200 px-2 py-1 rounded">123_Payment_Receipt.pdf</span>, where 123 is your <a href="https://cmt3.research.microsoft.com" className="text-blue-600 font-semibold hover:underline">CMT paper number</a>.
                </p>
                <p className="text-red-600 font-semibold italic">
                  If the invoice is not sent to the conference e-mail, the registration will not be granted and will be treated as invalid.
                </p>
              </div>
            </div>

            {/* Foreign Authors */}
            <div>
              <h3 className="text-base sm:text-lg md:text-xl font-bold text-gray-900 mb-3 sm:mb-4">
                For Foreign Authors
              </h3>
              <div className="space-y-2 sm:space-y-3 ml-4 sm:ml-6 text-gray-700 text-xs sm:text-sm md:text-base">
                <p className="font-semibold">Foreign authors are requested to pay the registration fees using the following bank details:</p>
                <div className="bg-white p-3 sm:p-4 rounded-lg border-l-4 border-blue-500 space-y-1 sm:space-y-2 text-xs sm:text-sm md:text-base">
                  <p><span className="font-bold">Name of the Beneficiary:</span> University of Engineering and Management, Kolkata</p>
                  <p><span className="font-bold">Name of the Bank:</span> Indian Overseas Bank, Sector - V, Salt Lake Branch</p>
                  <p><span className="font-bold">Beneficiary A/c. No:</span> 164201000001924 (Savings A/c.)</p>
                  <p><span className="font-bold">IFSC:</span> IOBA0001642</p>
                  <p><span className="font-bold">Swift Code:</span> IOBAINBB893</p>
                </div>
                <p>
                  After payment, the author must e-mail the <span className="font-bold">TRANSACTION ID</span> to <a href="mailto:aicare@uem.edu.in" className="text-blue-600 font-semibold hover:underline">aicare@uem.edu.in</a> along with their paper ID and title. The file should be in PDF format.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* WIE Special Discount */}
        <div className="mt-8 sm:mt-10 bg-gradient-to-r from-pink-50 to-purple-50 rounded-2xl shadow-xl p-6 sm:p-8 lg:p-12 text-center border-2 border-pink-200">
          <h2 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl font-bold text-purple-700 mb-3 sm:mb-4">✨ Special Discount for Women in Engineering</h2>
          <p className="text-gray-700 text-xs sm:text-sm md:text-base lg:text-lg mb-3 sm:mb-4 max-w-3xl mx-auto">
            We're offering an exclusive discount for women in the engineering field. This special rate is available for both student and non-student authors.
          </p>
          <p className="text-gray-700 text-xs sm:text-sm md:text-base lg:text-lg mb-4 sm:mb-6 max-w-3xl mx-auto">
            Don't miss out on this opportunity to be part of AICARE 2025 and contribute to the future of AI and engineering.
          </p>
          <a href="/wie" className="inline-block px-6 sm:px-8 py-2 sm:py-4 bg-gradient-to-r from-pink-600 to-purple-600 hover:from-pink-700 hover:to-purple-700 text-white font-bold text-xs sm:text-sm md:text-base lg:text-lg rounded-lg transition transform hover:scale-105">
            Learn More About WIE Discount →
          </a>
        </div>
      </div>

      {/* Yellow Marquee */}
      <marquee
        behavior=""
        direction="left"
        className="fixed bottom-0 left-0 right-0 bg-[#FFFF00] h-6 sm:h-8 lg:h-10 p-0.5 sm:p-1 z-50 text-black text-2xs sm:text-xs lg:text-lg font-bold whitespace-nowrap overflow-hidden"
      >
        <span className="animate-pulse text-red-600 font-extrabold inline-block">
          AICARE 2025 Topics (but not limited to):
        </span>
        <span className="inline-block ml-1 sm:ml-2">Applications of AI in Computing, UAV Networks, Astronomy, Renewable Energy.</span>
        <a href="/conference/tracks" className="text-red-600 underline font-extrabold animate-pulse ml-1 sm:ml-2 inline-block">
          View Tracks
        </a>
      </marquee>
    </div>
  );
};

export default Registration;
